name: First Github Actions Workflow

on: 
  push:

jobs:
  greet:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout Repository
       uses: actions/checkout@v4
       
     - name: Print Greeting 
       run: echo "hello from github actions!"

     - name: print date & time
       run: date 

     - name: print branch name 
       run: echo "branch: ${{ github.ref_name }}"

     - name:  print runner os & check docker version
       run: echo $RUNNER_OS && docker --version
    
