name: First Github Actions Workflow

on:
  push:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Greeting
        run: echo "hello from github actions!"

      - name: Print date & time
        run: date

      - name: Print branch name
        run: echo "branch: ${{ github.ref_name }}"

      - name: Print runner OS & check docker version
        run: |
          echo $RUNNER_OS
          docker --version
