name: Manual Workflow

on:
  workflow_dispatch:

    inputs:
      environment:
        description: "Choose Environment"
        required: true
        default: "staging"

jobs:
  manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Environment
        run: echo "Environment selected: ${{ github.event.inputs.environment }}"
