name: PR Check Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print PR Branch
        run: echo "PR check running for branch: ${{ github.head_ref }}"
